FROM datadog/agent:latest

# Fill manually (for security reasons):
ENV DD_API_KEY=

#VOLUME /var/run/docker.sock:/var/run/docker.sock:ro
#VOLUME /proc/:/host/proc/:ro
#VOLUME /opt/datadog-agent/run:/opt/datadog-agent/run:rw
#VOLUME /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
