FROM datadog/agent:latest

#VOLUME /var/run/docker.sock:/var/run/docker.sock:ro
#VOLUME /proc/:/host/proc/:ro
#VOLUME /opt/datadog-agent/run:/opt/datadog-agent/run:rw
#VOLUME /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

# Fill manually (for security reasons):
ENV DD_API_KEY=30ef1959f4e2c4aaddd09feadbc9e793
